# Generated by Django 6.0.2 on 2026-04-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole'), ('water', 'Water leak'), ('streetlight', 'Streetlight'), ('electricity', 'Electricity'), ('traffic', 'Traffic signals')], max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fault_uploads/%Y/%m/')),
                ('is_hazard', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='received', max_length=32)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
